name: Build Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches-ignore:
      - "*"

jobs:
  build-and-push-multiarch:
    if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU for Multi-Arch
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login Docker Hub (Optional)
        if: ${{ secrets.REGISTRY_USERNAME != '' && secrets.REGISTRY_PASSWORD != '' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Determine Tags
        id: meta
        run: |
          REPO_OWNER="${{ github.repository_owner }}"
          REF_NAME="${{ github.ref_name }}"
          TAGS="ghcr.io/${REPO_OWNER}/go-whatsapp-web-multidevice:${REF_NAME},ghcr.io/${REPO_OWNER}/go-whatsapp-web-multidevice:latest"
          
          if [ -n "${{ secrets.REGISTRY_USERNAME }}" ]; then
            TAGS="${TAGS},${{ secrets.REGISTRY_USERNAME }}/go-whatsapp-web-multidevice:${REF_NAME},${{ secrets.REGISTRY_USERNAME }}/go-whatsapp-web-multidevice:latest"
          fi
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

      - name: Build and Push Multi-Arch Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/golang.Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
